# Generated by Django 4.2 on 2023-05-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=10)),
                ('Last_Name', models.CharField(max_length=10)),
                ('Company', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_no', models.IntegerField()),
                ('Plans', models.CharField(choices=[('Business', 'Business'), ('Enterprise', 'Enterprise'), ('Other', 'Other')], default='Enterprise', max_length=10)),
                ('Msg', models.TextField()),
            ],
        ),
    ]
