# Generated by Django 4.2 on 2023-05-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('Productid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=10)),
                ('Price', models.IntegerField()),
                ('Review', models.CharField(max_length=5)),
            ],
        ),
    ]
