# Generated by Django 4.2 on 2023-05-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_prodpicmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdpicModel',
        ),
    ]
