# Generated by Django 4.2 on 2023-05-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdpicModel',
            new_name='ImageModel',
        ),
    ]
